# Feature Extraction from SMILES Data

This notebook extracts chemical features from SMILES (Simplified Molecular Input Line Entry System) strings for machine learning purposes.

**Goal:** Convert molecular structures into numerical features that can be used to predict if a molecule is biologically active.

### Import Required Libraries

- **pandas/numpy**: Data manipulation
- **sklearn**: Machine learning tools (for later use)
- **warnings**: Suppress warnings for cleaner output

In [8]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

## Step 1: Load Data

Load the training dataset containing SMILES strings and their activity labels.

In [9]:
orig_training_data = pd.read_csv("training_smiles.csv")

In [10]:
orig_training_data.shape

(202895, 3)

## Step 2: Convert SMILES to Molecule Objects

Convert SMILES strings (text representations of molecules) into RDKit molecule objects so we can extract chemical properties.

**Example:** `"CCO"` represents ethanol (ethyl alcohol)

In [11]:
orig_training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202895 entries, 0 to 202894
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   INDEX   202895 non-null  int64
 1   SMILES  202895 non-null  object
 2   ACTIVE  202895 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 4.6+ MB

Create a copy of the data for feature extraction.

In [12]:
features_df = orig_training_data.copy()

In [13]:
from rdkit import Chem


features_df["SMILES"] = features_df["SMILES"].astype("string")
features_df["MolFromSmiles"] = features_df["SMILES"].apply(Chem.MolFromSmiles)

[14:10:48] WARNING: not removing hydrogen atom without neighbors

In [ ]:
features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202895 entries, 0 to 202894
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   INDEX          202895 non-null  int64
 1   SMILES         202895 non-null  string
 2   ACTIVE         202895 non-null  float64
 3   MolFromSmiles  202895 non-null  object
dtypes: float64(1), int64(1), object(1), string(1)
memory usage: 6.2+ MB

:

In [14]:
features_df[:5]

,INDEX,SMILES,ACTIVE,MolFromSmiles
0,1,O=C(Nc1ccc2c(c1)OCCO2)C1CCN(c2ncccn2)CC1,0.0,<rdkit.Chem.rdchem.Mol object at 0x167143c30>
1,2,COCCCN1C(=O)C2C(C(=O)Nc3cccc(Cl)c3)C3C=CC2(O3)...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b65e0>
2,3,CCSc1ncc(Cl)c(C(=O)Nc2ccccc2C)n1,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6490>
3,4,COc1ccc2cc(/C=N/NC(=O)CN(c3ccccc3C)S(=O)(=O)c3...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6500>
4,5,CCCC(=O)Nc1nc2ccc(NC(=O)c3c(F)c(F)c(OC)c(F)c3F...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6570>

## Step 3: Extract Basic Molecular Features

Extract fundamental properties of each molecule:
- **NumAtoms**: Total number of atoms in the molecule
- **NumHeavyAtoms**: Number of heavy (non-hydrogen) atoms
- **NumBonds**: Total number of chemical bonds

In [18]:
features_df["NumAtoms"] = features_df["MolFromSmiles"].apply(lambda m: m.GetNumAtoms() if m is not None else None)
# same func found in lipnski
features_df["NumHeavyAtoms"] = features_df["MolFromSmiles"].apply(lambda m: m.GetNumHeavyAtoms() if m is not None else None)
features_df["NumBonds"] = features_df["MolFromSmiles"].apply(lambda m: m.GetNumBonds() if m is not None else None)
features_df.head()

,INDEX,SMILES,ACTIVE,MolFromSmiles,NumAtoms,NumBonds,NumHeavyAtoms
0,1,O=C(Nc1ccc2c(c1)OCCO2)C1CCN(c2ncccn2)CC1,0.0,<rdkit.Chem.rdchem.Mol object at 0x167143c30>,25,28,25
1,2,COCCCN1C(=O)C2C(C(=O)Nc3cccc(Cl)c3)C3C=CC2(O3)...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b65e0>,35,39,35
2,3,CCSc1ncc(Cl)c(C(=O)Nc2ccccc2C)n1,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6490>,20,21,20
3,4,COc1ccc2cc(/C=N/NC(=O)CN(c3ccccc3C)S(=O)(=O)c3...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6500>,36,39,36
4,5,CCCC(=O)Nc1nc2ccc(NC(=O)c3c(F)c(F)c(OC)c(F)c3F...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6570>,30,32,30

Check how many molecules have hydrogen atoms (NumAtoms != NumHeavyAtoms).

In [19]:
# only 6... not significant?
len(features_df.query('NumAtoms != NumHeavyAtoms'))

6

## Step 4: Extract Fragment Features

Identify specific chemical fragments/substructures in each molecule (e.g., benzene rings, aldehydes, alcohols).

These features help identify common chemical patterns that may be important for biological activity.

In [20]:
from rdkit.Chem import Fragments as f

frag_methods = [m for m in dir(f) if m.startswith("fr_")]

for frag in frag_methods:
    func = getattr(f, frag)
    features_df[frag] = features_df["MolFromSmiles"].apply(
        lambda m, fn=func: fn(m) if m is not None else None
    )

## Step 5: Extract Lipinski Features (Drug-Likeness)

Extract features based on **Lipinski's Rule of Five**, which predicts drug-likeness:
- **NumHDonors**: Number of hydrogen bond donors
- **NumHAcceptors**: Number of hydrogen bond acceptors
- **NumRotatableBonds**: Number of rotatable bonds (flexibility)
- **FractionCSP3**: Fraction of sp3 hybridized carbons
- And many more...

These features help predict if a molecule has properties suitable for oral drug administration.

In [21]:
from rdkit.Chem import Lipinski as l
test_mol = next(m for m in features_df["MolFromSmiles"] if m is not None)

numeric_lipinski = []
for name in dir(l):
    attr = getattr(l, name)
    if callable(attr):
        try:
            result = attr(test_mol)
            if isinstance(result, (int, float)):
                numeric_lipinski.append(name)
        except:
            pass 
                

print("Numeric Lipinski functions:", numeric_lipinski)

for func_name in numeric_lipinski:
    fn = getattr(l, func_name)
    features_df[func_name] = features_df["MolFromSmiles"].apply(
        lambda m, fn=fn: fn(m) if m is not None else None
    )

Numeric Lipinski functions: ['FractionCSP3', 'HeavyAtomCount', 'NHOHCount', 'NOCount', 'NumAliphaticCarbocycles', 'NumAliphaticHeterocycles', 'NumAliphaticRings', 'NumAmideBonds', 'NumAromaticCarbocycles', 'NumAromaticHeterocycles', 'NumAromaticRings', 'NumAtomStereoCenters', 'NumBridgeheadAtoms', 'NumHAcceptors', 'NumHDonors', 'NumHeteroatoms', 'NumHeterocycles', 'NumRotatableBonds', 'NumSaturatedCarbocycles', 'NumSaturatedHeterocycles', 'NumSaturatedRings', 'NumSpiroAtoms', 'NumUnspecifiedAtomStereoCenters', 'Phi', 'RingCount', '_cfn', '_fn']

## Step 6: Extract Advanced Molecular Descriptors

Extract ~40+ advanced molecular descriptors including:
- **Molecular weight** and **exact mass**
- **Polar surface area (TPSA)**: Important for membrane permeability
- **Chirality** and **stereochemistry** information
- **Ring counts** and **cycle types**
- **Topological indices** (connectivity, shape descriptors)
- And many more...

*Note: Some warnings about "no conformers" are expected - these descriptors require 3D structures, but we're using 2D information.*

In [22]:
import rdkit.Chem.rdMolDescriptors as d

test_mol = next(m for m in features_df["MolFromSmiles"] if m is not None)

numeric_rdmol= []
for name in dir(d):
    attr = getattr(d, name)
    if callable(attr):
        try:
            result = attr(test_mol)
            if isinstance(result, (int, float)):
                numeric_rdmol.append(name)
        except:
            pass 
                

print("Numeric RDMolDesc functions:", numeric_rdmol)

for func_name in numeric_rdmol:
    fn = getattr(d, func_name)
    features_df[func_name] = features_df["MolFromSmiles"].apply(
        lambda m, fn=fn: fn(m) if m is not None else None
    )

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 233 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/AUTOCORR3D.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 208 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 40 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/CoulombMat.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 235 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/EEM.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 192 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 1225 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/GETAWAY.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 177 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 172 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/MORSE.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 112 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 124 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 115 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PBF.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 136 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 145 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 154 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 192 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/RDF.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 165 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 226 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/PMI.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59]

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 382 in file /Users/runner/miniforge3/conda-bld/rdkit-meta_1764390867374/work/Code/GraphMol/Descriptors/WHIM.cpp
Failed Expression: mol.getNumConformers() >= 1
****

[14:29:59] DEPRECATION WARNING: please use AtomPairGenerator
[14:29:59] DEPRECATION WARNING: please use AtomPairGenerator
[14:29:59] DEPRECATION WARNING: please use AtomPairGenerator
[14:29:59] DEPRECATION WARNING: please use TopologicalTorsionGenerator
[14:29:59] DEPRECATION WARNING: please use TopologicalTorsionGenerator
[14:29:59] DEPRECATION WARNING: please use TopologicalTorsionGenerator

Numeric RDMolDesc functions: ['CalcChi0n', 'CalcChi0v', 'CalcChi1n', 'CalcChi1v', 'CalcChi2n', 'CalcChi2v', 'CalcChi3n', 'CalcChi3v', 'CalcChi4n', 'CalcChi4v', 'CalcExactMolWt', 'CalcFractionCSP3', 'CalcHallKierAlpha', 'CalcKappa1', 'CalcKappa2', 'CalcKappa3', 'CalcLabuteASA', 'CalcNumAliphaticCarbocycles', 'CalcNumAliphaticHeterocycles', 'CalcNumAliphaticRings', 'CalcNumAmideBonds', 'CalcNumAromaticCarbocycles', 'CalcNumAromaticHeterocycles', 'CalcNumAromaticRings', 'CalcNumAtomStereoCenters', 'CalcNumAtoms', 'CalcNumBridgeheadAtoms', 'CalcNumHBA', 'CalcNumHBD', 'CalcNumHeavyAtoms', 'CalcNumHeteroatoms', 'CalcNumHeterocycles', 'CalcNumLipinskiHBA', 'CalcNumLipinskiHBD', 'CalcNumRings', 'CalcNumRotatableBonds', 'CalcNumSaturatedCarbocycles', 'CalcNumSaturatedHeterocycles', 'CalcNumSaturatedRings', 'CalcNumSpiroAtoms', 'CalcNumUnspecifiedAtomStereoCenters', 'CalcPhi', 'CalcTPSA', '_CalcMolWt']

View summary of all extracted features. The dataset now contains ~163 columns with various molecular properties.

## Step 7: Save Features to CSV

Save all extracted features (~163 columns) to `training_features.csv` for use in machine learning models.

**Final dataset contains:**
- Original columns: INDEX, SMILES, ACTIVE
- ~160 new feature columns extracted from molecular structures

In [23]:
features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202895 entries, 0 to 202894
Columns: 163 entries, INDEX to _CalcMolWt
dtypes: float64(25), int64(136), object(1), string(1)
memory usage: 252.3+ MB

In [24]:
features_df.to_csv("training_features.csv")

In [25]:
features_df.head()

,INDEX,SMILES,ACTIVE,MolFromSmiles,NumAtoms,NumBonds,NumHeavyAtoms,fr_Al_COO,fr_Al_OH,fr_Al_OH_noTert,...,CalcNumRings,CalcNumRotatableBonds,CalcNumSaturatedCarbocycles,CalcNumSaturatedHeterocycles,CalcNumSaturatedRings,CalcNumSpiroAtoms,CalcNumUnspecifiedAtomStereoCenters,CalcPhi,CalcTPSA,_CalcMolWt
0,1,O=C(Nc1ccc2c(c1)OCCO2)C1CCN(c2ncccn2)CC1,0.0,<rdkit.Chem.rdchem.Mol object at 0x167143c30>,25,28,25,0,0,0,...,4,3,0,1,1,0,0,4.368063,76.58,340.383
1,2,COCCCN1C(=O)C2C(C(=O)Nc3cccc(Cl)c3)C3C=CC2(O3)...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b65e0>,35,39,35,0,0,0,...,5,8,1,2,3,1,5,6.877647,96.97,502.011
2,3,CCSc1ncc(Cl)c(C(=O)Nc2ccccc2C)n1,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6490>,20,21,20,0,0,0,...,2,4,0,0,0,0,0,4.977937,54.88,307.806
3,4,COc1ccc2cc(/C=N/NC(=O)CN(c3ccccc3C)S(=O)(=O)c3...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6500>,36,39,36,0,0,0,...,4,8,0,0,0,0,0,7.516779,100.96,523.014
4,5,CCCC(=O)Nc1nc2ccc(NC(=O)c3c(F)c(F)c(OC)c(F)c3F...,0.0,<rdkit.Chem.rdchem.Mol object at 0x1671b6570>,30,32,30,0,0,0,...,3,6,0,0,0,0,0,6.202841,80.32,441.406